// flow-typed signature: 12b4ca91908aecc6d3cca3ad4ca4108e
// flow-typed version: <<STUB>>/react-mobile-store-button_v^0.0.6/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-mobile-store-button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-mobile-store-button' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-mobile-store-button/example/src/App' {
  declare module.exports: any;
}

declare module 'react-mobile-store-button/example/src/App.test' {
  declare module.exports: any;
}

declare module 'react-mobile-store-button/example/src' {
  declare module.exports: any;
}

declare module 'react-mobile-store-button/example/src/registerServiceWorker' {
  declare module.exports: any;
}

declare module 'react-mobile-store-button/lib/MobileStoreButton' {
  declare module.exports: any;
}

declare module 'react-mobile-store-button/src/MobileStoreButton' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-mobile-store-button/example/src/App.js' {
  declare module.exports: $Exports<'react-mobile-store-button/example/src/App'>;
}
declare module 'react-mobile-store-button/example/src/App.test.js' {
  declare module.exports: $Exports<'react-mobile-store-button/example/src/App.test'>;
}
declare module 'react-mobile-store-button/example/src/index' {
  declare module.exports: $Exports<'react-mobile-store-button/example/src'>;
}
declare module 'react-mobile-store-button/example/src/index.js' {
  declare module.exports: $Exports<'react-mobile-store-button/example/src'>;
}
declare module 'react-mobile-store-button/example/src/registerServiceWorker.js' {
  declare module.exports: $Exports<'react-mobile-store-button/example/src/registerServiceWorker'>;
}
declare module 'react-mobile-store-button/index' {
  declare module.exports: $Exports<'react-mobile-store-button'>;
}
declare module 'react-mobile-store-button/index.js' {
  declare module.exports: $Exports<'react-mobile-store-button'>;
}
declare module 'react-mobile-store-button/lib/MobileStoreButton.js' {
  declare module.exports: $Exports<'react-mobile-store-button/lib/MobileStoreButton'>;
}
declare module 'react-mobile-store-button/src/MobileStoreButton.jsx' {
  declare module.exports: $Exports<'react-mobile-store-button/src/MobileStoreButton'>;
}
